name:  🕍 Acceso a la fortaleza Prohibida

on: push

jobs:
    acceso-a-la-base:
        runs-on: ubuntu-latest

        steps:
            - name: El agente llega al fortaleza
              run: |
                echo "Agente ${{ github.actor }} llega a la fortaleza"
                echo ""
                echo "Buscar los archivos de la liga"
                ls -la
                echo ""
                echo "❌ que paso?? No hay nada"

            - name: "Brainiac desbloquea la boveda"
              uses: actions/checkout@v4

            - name: "Ahora si, vamos a ver los planes"
              run: |
                echo "Buscar los archivos de la liga"
                ls -l
                echo "✅ Funciona!!!"
                echo ""
                echo "Planes:"
                ls planes/
                echo "Villanos:"
                ls miembros/
                echo "Inteligencia:"
                ls inteligencia/